### PR TITLE
Modified README

### LINKED ISSUE #30: Formatting README and Invalid Discord link
I think this repo requires a few corrections in the README and markdown modifications. Can I make a PR for the same?

Also the discord link given shows this when clicked:

image

### PR DESCRIPTION
**Pull request by uday03meh**
I have changed the formatting of README

I don't have discord link of the community so didn't update it.

Closes #30

### CODE REVIEW

**Review by kumar-kalyan — APPROVED** [review]
Please resolve conflicts

**Comment by uday03meh** [comment]
Okay, will work on them.

**Comment by uday03meh** [comment]
Hi, @kumar-kalyan
Can you share link to discord community as the one in README is invalid 

image

**Comment by kumar-kalyan** [comment]
Raise a new issue named fix discord link and asldd this link :
https://discord.gg/RJQ57S8NeF

**Comment by uday03meh** [comment]
Done, will make a PR once I'm assigned issue #47

**Comment by uday03meh** [comment]
Sure, will take care of it.

**Comment by uday03meh** [comment]
We can close this PR after accepting #48 PR

**Pull request closed without merging**
